# Generated by Django 4.0.7 on 2023-09-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('FatherName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('MailId', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('DateOfBirth', models.CharField(max_length=20)),
                ('BloodGroup', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
    ]
