# Generated by Django 4.0.7 on 2023-09-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='DateOfBirth',
            new_name='DOB',
        ),
    ]
